# Reference: http://www.appveyor.com/docs/appveyor-yml
# Notes:
#   - Indent each level of configuration with 2 spaces. Do not use tabs!

#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.{build}

branches:
  only:
    - master
  except:
    - old_master
    - gh-pages

#---------------------------------#
#    environment configuration    #
#---------------------------------#

shallow_clone: true

matrix:
  fast_finish: true

platform:
  - x86

configuration:
  - Release

environment:
  ENGINE_PATH: '%APPVEYOR_BUILD_FOLDER%\Engine'
  TESTS_PATH: '%APPVEYOR_BUILD_FOLDER%\Tests'
  FPC_PATH: '%APPVEYOR_BUILD_FOLDER%\fpc'
  COMPILER_PATH: '%APPVEYOR_BUILD_FOLDER%\fpc\bin\i386-win32'


build_script:
  - SET PATH=%PATH%;%COMPILER_PATH%
  - copy Tests\TERRATest.dpr Build
  - cd Build
  - compile_tests.bat
  - TERRATest.exe

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off

